#!/bin/sh
#pierwszy parametr pozycyjny - xml do przeczyszczenia z nieobsługiwanych znaków
#drugi parametr pozycyjny - plik z koordynatami prostokątów do 
python bad_xml.py $1 | python3 text_extractor.py $2 
