### MAKEFILE FOR PAGE ANALYSIS

DJVU_DIR=$(shell basename ${DJVU} .djvu)
GAZETTES=$(shell dirname "${DJVU}")


all: ${GAZETTES}/${DJVU_DIR}/page_${PAGE}.features.vw

.SECONDARY:

%/metadata.tsv:
	djvused -u ${DJVU} -e 'print-meta' > $@

%/metadata.vw: %/metadata.tsv
	python3 metadata_extraction.py < $< > $@

%/page_${PAGE}.full.tiff: ${DJVU}
	ddjvu -format=tiff -quality=60 -mode=color -page=${PAGE} $< $@

%/page_${PAGE}.xml: ${DJVU}
	djvutoxml --with-anno --with-text --page ${PAGE} $< $@

%/page_${PAGE}.rect: %/page_${PAGE}.full.tiff %/page_${PAGE}.xml
	cat $*/page_${PAGE}.xml | grep 'WORD' | sed 's,<WORD coords=",,g' | sed 's,".*,,g' | sed 's|,| |g' | python rectangle.skeleton.py -f $< -v > $@

%/page_${PAGE}.graphic_features.vw: %/page_${PAGE}.rect %/page_${PAGE}.full.tiff
	python graphic_feature_extraction.py -f $*/page_${PAGE}.full.tiff < $< > $@

%/page_${PAGE}.features.vw: %/page_${PAGE}.graphic_features.vw %/page_${PAGE}.rect %/metadata.vw
	paste $*/page_${PAGE}.rect $*/page_${PAGE}.graphic_features.vw | sed "s,^,$${DJVU}\t$$(cat $*/metadata.vw)\tPAGE:$${PAGE}\t,g" > $@
